/**
 * lib/profileSchema.js
 * Master applicant profile schema with default values
 */

export const defaultProfile = () => ({
  personal: {
    full_name: "",
    father_name: "",
    mother_name: "",
    dob: "",
    gender: "",
    category: "",
    sub_caste: "",
    religion: "",
    nationality: "Indian",
    marital_status: "",
    aadhaar: "",
    pan: "",
    identity_card_type: "", // Aadhaar, Voter ID, PAN, Passport, etc.
    identification_mark_1: "",
    identification_mark_2: "",
    salutation: "", // Shri, Shrimati, Kumari, etc.
    husband_name: "",
    residence_type: "", // Permanent, Temporary, Sthayi, Asthayi
    profession: "", // Student, Govt Service, Private Service, Business, Farmer, etc.
    caste_details: {
      category: "", // SC, ST, OBC, EBC, General
      caste: "",
      caste_serial_no: "",
      sub_caste: "",
      sub_caste_serial_no: "",
    },
    income_details: {
      govt_service: "",
      agriculture: "",
      business: "",
      other_sources: "",
      total_annual: "",
    }
  },
  contact: {
    mobile: "",
    alternate_mobile: "",
    email: "",
    permanent_address: {
      line1: "",
      village_town: "",
      ward_no: "",
      post_office: "",
      police_station: "",
      tehsil: "",
      sub_division: "",
      block: "",
      local_body_type: "", // Gram Panchayat, Municipal Corporation, Municipality, Town Panchayat
      city: "",
      district: "",
      state: "",
      pincode: "",
    },
    residence_history: [
      {
        address: "",
        district: "",
        police_station: "",
        from_month: "",
        from_year: "",
        to_month: "",
        to_year: "",
      }
    ],
    correspondence_address: { same_as_permanent: true },
  },
  education: [
    {
      level: "10th",
      board: "",
      board_type: "", // Central or State
      school: "",
      school_code: "",
      center_code: "",
      roll_no: "",
      month_of_passing: "",
      year_of_passing: "",
      subjects: [], // { name, marks_obtained, max_marks }
      marks_obtained: "",
      total_marks: "",
      percentage: "",
      cgpa: "",
      division: "",
      certificate_number: "",
      issue_date: "",
    },
    {
      level: "12th",
      board: "",
      board_type: "", // Central or State
      school: "",
      school_code: "",
      stream: "",
      roll_no: "",
      month_of_passing: "",
      year_of_passing: "",
      subjects: [], // { name, marks_obtained, max_marks }
      marks_obtained: "",
      total_marks: "",
      percentage: "",
      cgpa: "",
      division: "",
      certificate_number: "",
      issue_date: "",
    },
    {
      level: "Graduation",
      university: "",
      college: "",
      college_code: "",
      enrollment_no: "",
      registration_no: "",
      degree: "", // e.g. BA, BSc, BTech
      branch: "",
      month_of_passing: "",
      year_of_passing: "",
      percentage: "",
      cgpa: "",
      division: "",
      certificate_number: "",
      degree_number: "",
      issue_date: "",
      signatory_title: "", // Registrar or Vice Chancellor
    },
    {
      level: "Diploma",
      university: "",
      college: "",
      roll_no: "",
      course_name: "",
      year_of_passing: "",
      percentage: "",
      certificate_number: "",
      issue_date: "",
    },
    {
      level: "Post Graduation",
      university: "",
      college: "",
      degree: "",
      branch: "",
      year_of_passing: "",
      percentage: "",
      certificate_number: "",
      issue_date: "",
    },
  ],
  certificates: {
    category: {
      category_name: "", // SC, ST, OBC, EWS, General
      sub_caste: "",
      certificate_number: "",
      reference_number: "",
      token_number: "",
      issue_date: "",
      validity_date: "",
      issuing_authority: "", // Revenue Officer, SDM, Collector, DM
      issuing_authority_designation: "",
      issuing_office: "",
      district: "",
      state: "",
      mother_name: "",
      father_name: "",
      address: "",
    },
    domicile: {
      certificate_number: "",
      issue_date: "",
      validity_date: "",
      issuing_authority: "",
      issuing_office: "",
      district: "",
      state: "",
      duration_of_residence: "",
    },
    income: {
      annual_income: "",
      annual_income_words: "",
      certificate_number: "",
      issue_date: "",
      issuing_authority: "",
      issuing_office: "",
      district: "",
      state: "",
    },
    other: [],
  },
  documents: {
    photo: { original_path: "", dimensions: "", target_dimensions: "", size_kb: "", target_size_kb: "" },
    signature: { original_path: "", dimensions: "", target_dimensions: "", size_kb: "", target_size_kb: "" },
    files: {
      aadhaar: "",
      pan: "",
      "10th_marksheet": "",
      "10th_certificate": "",
      "12th_marksheet": "",
      "12th_certificate": "",
      graduation_certificate: "",
      category_certificate: "",
      domicile_certificate: "",
      income_certificate: "",
      computer_certificate: "",
      other: [],
    },
  },
  _meta: {
    created_at: "",
    updated_at: "",
    confidence: {},
  },
});

export const DOCUMENT_TYPES = [
  { id: "aadhaar", label: "Aadhaar Card", icon: "🪪" },
  { id: "pan", label: "PAN Card", icon: "💳" },
  { id: "10th_marksheet", label: "10th Marksheet", icon: "📄" },
  { id: "10th_certificate", label: "10th Certificate", icon: "🏆" },
  { id: "12th_marksheet", label: "12th Marksheet", icon: "📄" },
  { id: "12th_certificate", label: "12th Certificate", icon: "🏆" },
  { id: "graduation_certificate", label: "Graduation Certificate", icon: "🎓" },
  { id: "category_certificate", label: "Category/Caste Certificate", icon: "📋" },
  { id: "domicile_certificate", label: "Domicile Certificate", icon: "🏠" },
  { id: "income_certificate", label: "Income Certificate", icon: "💰" },
  { id: "computer_certificate", label: "Computer Certificate (e.g. ADCA)", icon: "💻" },
  { id: "photo", label: "Applicant Photo", icon: "🖼️" },
  { id: "signature", label: "Applicant Signature", icon: "✍️" },
  { id: "other", label: "Other Certificate", icon: "📑" },
];
