/**
 * lib/profileSchema.js
 * Master applicant profile schema with default values
 */

export const defaultProfile = () => ({
  personal: {
    full_name: "",
    father_name: "",
    mother_name: "",
    dob: "",
    gender: "",
    category: "",
    sub_caste: "",
    religion: "",
    nationality: "Indian",
    marital_status: "",
    aadhaar: "",
    pan: "",
  },
  contact: {
    mobile: "",
    alternate_mobile: "",
    email: "",
    permanent_address: {
      line1: "",
      village_town: "",
      post_office: "",
      tehsil: "",
      city: "",
      district: "",
      state: "",
      pincode: "",
    },
    correspondence_address: { same_as_permanent: true },
  },
  education: [
    {
      level: "10th",
      board: "",
      school: "",
      school_code: "",
      center_code: "",
      roll_no: "",
      year_of_passing: "",
      subjects: [],
      marks_obtained: "",
      total_marks: "",
      percentage: "",
      cgpa: "",
      division: "",
      certificate_number: "",
      issue_date: "",
    },
    {
      level: "12th",
      board: "",
      school: "",
      school_code: "",
      stream: "",
      roll_no: "",
      year_of_passing: "",
      subjects: [],
      marks_obtained: "",
      total_marks: "",
      percentage: "",
      cgpa: "",
      division: "",
      certificate_number: "",
      issue_date: "",
    },
    {
      level: "Graduation",
      university: "",
      college: "",
      college_code: "",
      enrollment_no: "",
      registration_no: "",
      degree: "",
      branch: "",
      year_of_passing: "",
      percentage: "",
      cgpa: "",
      division: "",
      certificate_number: "",
      degree_number: "",
      issue_date: "",
    },
  ],
  certificates: {
    category: {
      category_name: "",
      sub_caste: "",
      certificate_number: "",
      issue_date: "",
      validity_date: "",
      issuing_authority: "",
      issuing_office: "",
      district: "",
      state: "",
      purpose: "",
    },
    domicile: {
      certificate_number: "",
      issue_date: "",
      validity_date: "",
      issuing_authority: "",
      issuing_office: "",
      district: "",
      state: "",
      duration_of_residence: "",
    },
    income: {
      annual_income: "",
      annual_income_words: "",
      certificate_number: "",
      issue_date: "",
      issuing_authority: "",
      issuing_office: "",
      district: "",
      state: "",
    },
    other: [],
  },
  documents: {
    photo: { original_path: "", dimensions: "", size_kb: "" },
    signature: { original_path: "", dimensions: "", size_kb: "" },
    files: {
      aadhaar: "",
      pan: "",
      "10th_marksheet": "",
      "10th_certificate": "",
      "12th_marksheet": "",
      "12th_certificate": "",
      graduation_certificate: "",
      category_certificate: "",
      domicile_certificate: "",
      income_certificate: "",
      other: [],
    },
  },
  _meta: {
    created_at: "",
    updated_at: "",
    confidence: {},
  },
});

export const DOCUMENT_TYPES = [
  { id: "aadhaar", label: "Aadhaar Card", icon: "🪪" },
  { id: "pan", label: "PAN Card", icon: "💳" },
  { id: "10th_marksheet", label: "10th Marksheet", icon: "📄" },
  { id: "10th_certificate", label: "10th Certificate", icon: "🏆" },
  { id: "12th_marksheet", label: "12th Marksheet", icon: "📄" },
  { id: "12th_certificate", label: "12th Certificate", icon: "🏆" },
  { id: "graduation_certificate", label: "Graduation Certificate", icon: "🎓" },
  { id: "category_certificate", label: "Category/Caste Certificate", icon: "📋" },
  { id: "domicile_certificate", label: "Domicile Certificate", icon: "🏠" },
  { id: "income_certificate", label: "Income Certificate", icon: "💰" },
  { id: "photo", label: "Applicant Photo", icon: "🖼️" },
  { id: "signature", label: "Applicant Signature", icon: "✍️" },
  { id: "other", label: "Other Certificate", icon: "📑" },
];
